spring:
  application.name: meetup-authorization-server
 
server:
  port: 8080
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG


auth:
  client:
    id: client
    secret: secret
  redirect:
    uri: http://localhost:3000/api/auth/callback/springAuth